"""empty message

Revision ID: 23f99b55e3d2
Revises: b6bb18ed643e
Create Date: 2022-05-05 11:59:31.574466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f99b55e3d2'
down_revision = 'b6bb18ed643e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('products', sa.Column('available', sa.Boolean(), nullable=False))
    op.drop_column('products', 'status')
    op.add_column('rooms', sa.Column('available', sa.Boolean(), nullable=False))
    op.drop_column('rooms', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('rooms', 'available')
    op.add_column('products', sa.Column('status', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.drop_column('products', 'available')
    op.drop_table('products_categories')
    # ### end Alembic commands ###