"""empty message

Revision ID: 44290148ae23
Revises: 23f99b55e3d2
Create Date: 2022-05-05 14:06:10.460951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44290148ae23'
down_revision = '23f99b55e3d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_categories', sa.Column('category_id', sa.Integer(), nullable=False))
    op.drop_constraint('products_categories_room_id_fkey', 'products_categories', type_='foreignkey')
    op.create_foreign_key(None, 'products_categories', 'categories', ['category_id'], ['id'])
    op.drop_column('products_categories', 'room_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_categories', sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products_categories', type_='foreignkey')
    op.create_foreign_key('products_categories_room_id_fkey', 'products_categories', 'rooms', ['room_id'], ['id'])
    op.drop_column('products_categories', 'category_id')
    # ### end Alembic commands ###