"""added table categories

Revision ID: 485f4e2dc34f
Revises: e2e71ff53823
Create Date: 2022-05-03 11:42:27.855393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485f4e2dc34f'
down_revision = 'e2e71ff53823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    # ### end Alembic commands ###
