"""creating address and products tables

Revision ID: 56087abd9bfc
Revises: 
Create Date: 2022-04-26 16:14:00.072731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56087abd9bfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('cidade', sa.String(length=20), nullable=True),
    sa.Column('rua', sa.String(length=30), nullable=True),
    sa.Column('numero', sa.String(length=5), nullable=True),
    sa.Column('complemento', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('prince', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('addresses')
    # ### end Alembic commands ###
