"""empty message

Revision ID: b6bb18ed643e
Revises: 29aea221a132
Create Date: 2022-05-04 11:24:17.150710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6bb18ed643e'
down_revision = '29aea221a132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rentals', 'quantity')
    # ### end Alembic commands ###
