"""create table addresses

Revision ID: e64e58ca0c75
Revises: a5c59cb6281f
Create Date: 2022-04-28 10:02:06.581624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e64e58ca0c75'
down_revision = 'a5c59cb6281f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('cidade', sa.String(length=20), nullable=True),
    sa.Column('rua', sa.String(length=20), nullable=True),
    sa.Column('numero', sa.String(length=8), nullable=True),
    sa.Column('complemento', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addresses')
    # ### end Alembic commands ###
