"""adding foreing_key(addresses) on products table

Revision ID: f5257b11303a
Revises: 56087abd9bfc
Create Date: 2022-04-26 16:19:34.416613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f5257b11303a'
down_revision = '56087abd9bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('address_id', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'products', 'addresses', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'address_id')
    # ### end Alembic commands ###
